CREATE TABLE IF NOT EXISTS "PDFToClient"
(
    "PDFDeliverId" SERIAL PRIMARY KEY,
    "EventId" VARCHAR(40),
    "EvaluationId" BIGINT NOT NULL,
    "DeliveryDateTime" TIMESTAMP WITH TIME ZONE,
    "DeliveryCreatedDateTime" TIMESTAMP WITH TIME ZONE,
    "BatchId" BIGINT NOT NULL,
    "BatchName" VARCHAR(200),
    "CKDId" INTEGER NOT NULL REFERENCES "CKD"("CKDId"),
    "CreatedDateTime" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 


INSERT INTO "CKDStatusCode" ("CKDStatusCodeId", "StatusCode") VALUES  (6, 'BillableEventRecieved') ON CONFLICT ("CKDStatusCodeId") DO NOTHING;

CREATE TABLE IF NOT EXISTS "CKDRCMBilling"
(
    "Id" SERIAL PRIMARY KEY,
    "BillId" VARCHAR(50),
    "CKDId" INTEGER NOT NULL REFERENCES "CKD"("CKDId"),
    "CreatedDateTime" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);