CREATE TABLE "ProviderPay"
(
    "Id" SERIAL PRIMARY KEY,
    "PaymentId" VARCHAR(50) NOT NULL,
    "FOBTId" INTEGER NOT NULL REFERENCES "FOBT"("FOBTId"),
    "CreatedDateTime" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);