ALTER TABLE public."FOBTBilling" ADD COLUMN "Accepted" BOOLEAN NULL;
ALTER TABLE public."FOBTBilling" ADD COLUMN "AcceptedAt" TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE public."FOBTBilling" ALTER COLUMN "Accepted" SET DEFAULT FALSE;