ALTER TABLE "PAD" ALTER COLUMN "LeftScoreAnswerValue" DROP NOT NULL;

ALTER TABLE "PAD" ALTER COLUMN "LeftSeverityAnswerValue" DROP NOT NULL;

ALTER TABLE "PAD" ALTER COLUMN "RightScoreAnswerValue" DROP NOT NULL;

ALTER TABLE "PAD" ALTER COLUMN "RightSeverityAnswerValue" DROP NOT NULL;
