ALTER TABLE public."PADRCMBilling" ADD COLUMN "Accepted" BOOLEAN NULL;
ALTER TABLE public."PADRCMBilling" ADD COLUMN "AcceptedAt" TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE public."PADRCMBilling" ALTER COLUMN "Accepted" SET DEFAULT FALSE;