ALTER TABLE public."DEEBilling" ADD COLUMN "Accepted" BOOLEAN NULL;
ALTER TABLE public."DEEBilling" ADD COLUMN "AcceptedAt" TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE public."DEEBilling" ALTER COLUMN "Accepted" SET DEFAULT FALSE;

GRANT SELECT, UPDATE, INSERT ON public."DEEBilling" TO svcdee;