CREATE TABLE public."Hold"
(
	"HoldId" SERIAL PRIMARY KEY NOT NULL,
	"CdiHoldId" UUID NOT NULL UNIQUE,
	"EvaluationId" INTEGER NOT NULL UNIQUE,
	"ExpiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
	"HeldOnDateTime" TIMESTAMP WITH TIME ZONE NOT NULL,
	"SentAtDateTime" TIMESTAMP WITH TIME ZONE NOT NULL,
	"ReleasedDateTime" TIMESTAMP WITH TIME ZONE NULL,
	"CreatedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IDX_Hold_EvaluationId ON public."Hold" ("EvaluationId");