parameters:
  - name: envVars
    type: object
    default:
      - name: OKTA_PASSWORD
        value: $(OKTA_PASSWORD)
      - name: OKTA_USERNAME
        value: $(OKTA_USERNAME)
      - name: KAFKA_PASSWORD
        value: $(KAFKA_PASSWORD)
      - name: KAFKA_USERNAME
        value: $(KAFKA_USERNAME)
      - name: KAFKA_PUB_PASSWORD
        value: $(KAFKA_PUB_PASSWORD)
      - name: KAFKA_PUB_USERNAME
        value: $(KAFKA_PUB_USERNAME)
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: $(KAFKA_BOOTSTRAP_SERVERS)
      - name: KAFKA_GROUP_ID
        value: $(KAFKA_GROUP_ID)
      - name: SPIROMETRY_DB_USERNAME
        value: $(PostgresUser)
      - name: SPIROMETRY_DB_PASSWORD
        value: $(PostgresPassword)
      - name: SPIROMETRY_DB_HOST
        value: $(SPIROMETRY_DB_HOST)
      - name: LD_SDK_KEY
        value: $(LD_SDK_KEY)
      - name: LD_USER_KEY
        value: $(LD_USER_KEY)
      - name: LD_USERNAME
        value: $(LD_USERNAME)
      - name: SERVICE
        value: spirometry
      - name: DOTNET_CLI_HOME
        value: '$(Agent.TempDirectory)'
  - name: runSettingsFilePath
    type: string
    default: $(Build.Repository.Name)/service/spirometry/src/Signify.Spirometry.Svc.System.Tests/RunSettings/uat.runsettings
  - name: testCycleName
    type: string
    default: 'Test Automation Run for Commit : $(Build.SourceVersion) (SPIROMETRY)'
  - name: dotnetVersion
    type: string
    default: '8.0.x'
  - name: flyway
    type: boolean
    default: false  

jobs:
  - job: Dotnet_System_Tests
    displayName: Dotnet.System.Tests
    pool: uat-linux-test
    variables:
      - group: qe-common-zephyr
      - name: testFilter
        ${{ if eq(parameters.flyway, true) }}:
          value: '"TestCategory=regression|TestCategory=database"'
        ${{else}}:
          value: '"TestCategory=regression"'
    steps:
      - checkout: self
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '${{ parameters.dotnetVersion }}'
      - task: DotNetCoreCLI@2
        displayName: dotnet test
        inputs:
          command: test
          projects: $(Build.SourcesDirectory)/$(Build.Repository.Name)/service/spirometry/src/Signify.Spirometry.Svc.System.Tests/Signify.Spirometry.Svc.System.Tests.csproj
          arguments: '--configuration Test -s ${{parameters.runSettingsFilePath}} --logger:"console;verbosity=detailed" --filter ${{variables.testFilter}}'
          publishTestResults: true
          nobuild: false
        env:
          ${{ each envVariable in parameters.envVars }}:
            ${{ envVariable.name }}: ${{ envVariable.value }}
      - template: steptemplates/zephyr-create-test-cycle.yaml@templates
        parameters:
          zephyrApiUrl: '$(ZEPHYR_API_URL)ANC'
          zephyrApiToken: $(ZEPHYR_API_TOKEN)
          testResultsFilePath: '$(Agent.TempDirectory)/*.trx'
          jiraProjectKey: 'ANC'
          testCycleName: ${{ parameters.testCycleName }}      
