trigger:
  batch: "true"
  paths:
    include:
      - service/spirometry/flyway/*

resources:
  repositories:
    - repository: templates
      type: git
      name: HCC/templates

pool:
  name: $(azdo-linux-agent-pool)

variables:
  - group: azuredevops
  - name: appName
    value: 'spirometry'
  - name: rootFolder
    value: 'service'
  - name: vmImageName
    value: 'prod-linux-build'
  - name: DOTNET_CLI_HOME
    value: /tmp

stages:
  - stage: 'buildCI'
    jobs:
      - job: BuildAndTestCI
        steps:
          - template: steptemplates/ST_flywaydb.yaml@templates  # Template reference
            parameters:
              workingdir: '$(rootFolder)/$(appName)'
              flywayfolder: 'flyway'