parameters:
  - name: envVars
    type: object
    default:
      - name: OKTA_PASSWORD
        value: $(OKTA_PASSWORD)
      - name: OKTA_USERNAME
        value: $(OKTA_USERNAME)
      - name: OKTA_CLIENT_ID
        value: $(OKTA_CLIENT_ID)
      #      - name: KAFKA_PASSWORD
      #        value: $(KAFKA_PASSWORD)
      #      - name: KAFKA_USERNAME
      #        value: $(KAFKA_USERNAME)
      #      - name: KAFKA_PUB_PASSWORD
      #        value: $(KAFKA_PUB_PASSWORD)
      #      - name: KAFKA_PUB_USERNAME
      #        value: $(KAFKA_PUB_USERNAME)
      #      - name: KAFKA_BOOTSTRAP_SERVERS
      #        value: $(KAFKA_BOOTSTRAP_SERVERS)
      #      - name: KAFKA_GROUP_ID
      #        value: $(KAFKA_GROUP_ID)
      - name: FOBT_DB_USERNAME
        value: $(FOBT_DB_USERNAME)
      - name: FOBT_DB_PASSWORD
        value: $(FOBT_DB_PASSWORD)
      - name: FOBT_DB_HOST
        value: $(FOBT_DB_HOST)
      - name: LD_SDK_KEY
        value: $(LD_SDK_KEY)
      - name: LD_USER_KEY
        value: $(LD_USER_KEY)
      - name: LD_USERNAME
        value: $(LD_USERNAME)
      - name: SERVICE
        value: fobt
      - name: DOTNET_CLI_HOME
        value: '$(Agent.TempDirectory)'
  - name: runSettingsFilePath
    type: string
    default: $(Build.Repository.Name)/service/fobt/src/Signify.FOBT.Svc.System.Tests/RunSettings/prod.runsettings
  - name: testCycleName
    type: string
    default: 'Test Automation Run for Commit : $(Build.SourceVersion) (FOBT)-PROD'
  - name: flyway
    type: boolean
    default: false

jobs:
  - template: jobtemplates/dotnet-system-tests.yaml@templates
    parameters:
      createTestCycle: true
      ${{ if eq(parameters.flyway, true) }}:
        dotNetTestArguments: '-s ${{parameters.runSettingsFilePath}} --logger:"junit;LogFilePath=TestResults/TestResultsJunit.xml" --logger:"console;verbosity=detailed" --filter "TestCategory=prod_smoke|TestCategory=database"'
      ${{else}}:
        dotNetTestArguments: '-s ${{parameters.runSettingsFilePath}} --logger:"junit;LogFilePath=TestResults/TestResultsJunit.xml" --logger:"console;verbosity=detailed" --filter "TestCategory=prod_smoke"'
      jiraProjectKey: 'ANC'
      testResultDir: $(Build.Repository.Name)/service/fobt/src/Signify.FOBT.Svc.System.Tests/TestResults
      csprojPath: $(Build.Repository.Name)/service/fobt/src/Signify.FOBT.Svc.System.Tests/Signify.FOBT.Svc.System.Tests.csproj
      envVariables: ${{ parameters.envVars }}
      testCycleName: ${{ parameters.testCycleName }}