trigger:
  batch: "true"
  paths:
    include:
      - service/fobt/*
    exclude:
      - service/fobt/docs/*
      - service/fobt/flyway/*
      - service/fobt/tf/*
      - service/fobt/catalog-info.yaml
      - service/fobt/mkdocs.yaml
      - service/fobt/readme.md

resources:
  repositories:
    - repository: templates
      type: git
      name: HCC/templates

variables:
  - group: azuredevops
  - group: dps-shared-all
  - name: rootFolder
    value: 'service'
  - name: appName
    value: 'fobt'
  - name: Sln
    value: 'Signify.FOBT.Svc.sln'
  - name: projectName
    value: 'signify-fobt-svc'

stages:
  - template: stagetemplates/dotnet-docker.yaml@templates
    parameters:
      coreVersion: 8.0.x
      gitVersionFile: $(rootFolder)/$(appName)/GitVersion.yaml
      dockerComposeFile: $(rootFolder)/$(appName)/docker-compose.yaml
      dockerComposeService: signify-fobt-svc
      kubernetesManifest: $(rootFolder)/$(appName)/k8s/deployment.yaml
      solutionPath: $(rootFolder)/$(appName)/src/$(Sln)
      projectName: $(projectName)
      dotNetTestArguments: --filter FullyQualifiedName!~Signify.FOBT.Svc.System.Tests
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}: 
        push: false 
      dockerCustomSteps:
      # Adds a build tag from the full commit SHA of this build.
      #
      # This can be used to reference the precise build during deployment by
      # other pipelines.
      - task: Bash@3
        displayName: 'Tag build'
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[build.addbuildtag]$(Build.SourceVersion)"
            
  # TODO: 2023/11/22 - SRE's working on snyk integration to templates. 
  # TODO: SRE-4917 - Create Snyk templates
  # - stage: 'SecurityScan'
  #   variables:
  #     - group: DPS-Snyk
  #   jobs:
  #   - job: SnykSecurityScan
  #     steps:
  #     - task: SnykSecurityScan@1
  #       inputs:
  #         serviceConnectionEndpoint: 'Snyk DPS'
  #         testType: app
  #         testDirectory: $(rootFolder)/$(appName)/src/$(Sln)
  #         monitorWhen: always
  #         failOnIssues: false
  #         organization: $(SnykOrgId)
  #         projectName: Signify.FOBT.Svc