host_name = "localhost"
user_name = "serviceuser"
user_password = "abc123"
ssl_mode = "disable"
app_name = "servicesample"
admin_username = "postgres"
admin_password = "postgrespassword"
database_name = "servicesample"