version: '3.7'

services:
  signify-uACR-svc:
    image: signifyhealth.azurecr.io/signify-uacr-svc:${TAG}
    environment:
      - DOTNET_ENVIRONMENT=Development
    ports:
      - '5000:5000'
    build:
      context: ./src
      #path to Dockerfile is relative to the context path set above
      dockerfile: ./Signify.uACR.Svc/Dockerfile
      args:
        PROJECT_NAME: Signify.uACR.Svc

