CREATE TABLE IF NOT EXISTS "HBA1CPOCRCMBilling"
(
    "Id" SERIAL PRIMARY KEY,
    "BillId" VARCHAR(50),
    "HBA1CPOCId" INTEGER NOT NULL REFERENCES "HBA1CPOC"("HBA1CPOCId"),
    "CreatedDateTime" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);