CREATE TABLE "ProviderPay"
(
    "ProviderPayId" SERIAL PRIMARY KEY,
    "PaymentId" VARCHAR(50) NOT NULL,
    "HBA1CPOCId" INTEGER NOT NULL REFERENCES "HBA1CPOC"("HBA1CPOCId"),
    "CreatedDateTime" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);