ALTER TABLE public."HBA1CPOCRCMBilling" ADD COLUMN "Accepted" BOOLEAN NULL;
ALTER TABLE public."HBA1CPOCRCMBilling" ADD COLUMN "AcceptedAt" TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE public."HBA1CPOCRCMBilling" ALTER COLUMN "Accepted" SET DEFAULT FALSE;