@ignore
@envnot=prod
Feature: Create providers based on the configuration

    Background:
        * eval if (env == 'prod') karate.abort();
        * def DataGen = function() { var DataGen = Java.type('helpers.data.DataGen'); return new DataGen(); }
        * def Faker = function() { var Faker = Java.type('helpers.data.Faker'); return new Faker(); }
        * configure retry = { count: 5, interval: 1000 }

        * def providerConfig =
            """
            {
            planId: 37,
            providerLicensedState: 'TX',
            trainingTypeId: 2,
            capacityPlanConfigs: [ { planId: 37, locationType: 1, startDay: 0, endDay: 1} ]
            }
            """

        * def providerDetails =
            """
            {
                "recruiterUserId": 1,
                "recruiterInTrainingId": 1,
                "recruiterOktaUserId": "0oaq0wnz6kZOdapot0h7",
                "recruiterInTrainingOktaUserId": "0oaq0wnz6kZOdapot0h7",
                "oktaUserId": "0oaq0wnz6kZOdapot0h7",
                "firstName": "#(Faker().firstName())",
                "lastName": "#(Faker().lastName())",
                "middleName": "",
                "degree": "MD",
                "nationalProviderIdentifier": "#(Faker().randomDigit(10))",
                "employeeType": 1,
                "primaryPhone": "0000000000",
                "secondaryPhone": "",
                "personalEmail": "ancillary-services-karate@signifyhealth.com",
                "gender": 1,
                "providerStatusId": 1,
                "averageEvaluationTimeInMinutes": 30,
                "primaryLanguage": 1,
                "secondaryLanguage": 0,
                "addressLineOne": "4055 Valley View ln",
                "addressLineTwo": "",
                "city": "Dallas",
                "state": "TX",
                "zipCode": "75244",
                "censeoHealthEmail": "ancillary-services-karate@signifyhealth.com",
                "specialization": "Family Practice",
                "dateOfBirth": "1980-01-01",
                "qaTrainingStatus": 2
            }
            """

    Scenario: Create provider and capacity based on configuration
        # Create the provider
        Given url providerApi
        And path 'Providers'
        And request providerDetails
        And retry until responseStatus == 200   
        When method POST
        Then status 200
        * providerDetails.providerId = response.providerId
        * set providerDetails.signature = '/9j/4AAQSkZJRgABAQAASABIAAD/4Qk0RXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAABJKGAAcAAAjQAAAAXKABAAMAAAABAAEAAKACAAQAAAABAAACeqADAAQAAAABAAAA4gAAAABBU0NJSQAAAFluQnNhWE4wTUREVUFRSURCQVVHQndwWUpIWmxjbk5wYjI1WkpHRnlZMmhwZG1WeVZDUjBiM0JZSkc5aWFtVmpkSE1TQUFHR29GOFFEMDVUUzJWNVpXUkJjbU5vYVhabGN0RUlDVlJ5YjI5MGdBR3BDd3dURnlrdE5UazhWU1J1ZFd4czBnME9EeEphVGxNdWIySnFaV04wYzFZa1kyeGhjM09pRUJHQUFvQUlnQWZTRFE0VUVxRVZnQU9BQjlvT0dCa2FHeHdkSGg4Z0lTSWlJeVFsSWlZbktGOFFIRlZKUW1WNmFXVnlVR0YwYUV4cGJtVktiMmx1VTNSNWJHVkxaWGxmRUNOVlNVSmxlbWxsY2xCaGRHaE1hVzVsUkdGemFGQmhkSFJsY201RGIzVnVkRXRsZVY4UUdWVkpRbVY2YVdWeVVHRjBhRTFwZEdWeVRHbHRhWFJMWlhsZkVCbFZTVUpsZW1sbGNsQmhkR2hEUjFCaGRHaEVZWFJoUzJWNVh4QWNWVWxDWlhwcFpYSlFZWFJvVEdsdVpVUmhjMmhRYUdGelpVdGxlVjhRRzFWSlFtVjZhV1Z5VUdGMGFFeHBibVZEWVhCVGRIbHNaVXRsZVY4UUdGVkpRbVY2YVdWeVVHRjBhRXhwYm1WWGFXUjBhRXRsZVY4UUYxVkpRbVY2YVdWeVVHRjBhRVpzWVhSdVpYTnpTMlY1WHhBaVZVbENaWHBwWlhKUVlYUm9WWE5sYzBWMlpXNVBaR1JHYVd4c1VuVnNaVXRsZVlBR0VBQWlRU0FBQUlBRUlnQUFBQUFpUUFBQUFDSS9HWm1hQ05JcURpc3NWMDVUTG1SaGRHRlBFUU9RQUFBQUFBRUFBQUFBQUY5REFBQ0VRZ01BQUFBREFBQUFBSUJmUXdBQXBVSUFnR0ZEQUFEblFnQ0FhRU1Bd0ExREFBQUFBQUVBQUFBQWdHaERBTUFOUXdNQUFBQURBQUFBQUlCdlF3QUFLRU1BZ0hsREFJQTZRd0RnZ0VNQXdEOURBQUFBQUFFQUFBQUE0SUJEQU1BL1F3TUFBQUFEQUFBQUFBQ0ZRd0FBUlVNQXdJZERBQUE3UXdDQWlFTUFBQ0pEQUFBQUFBRUFBQUFBZ0loREFBQWlRd01BQUFBREFBQUFBRUNKUXdBQUNVTUFRSWxEQUFEV1FnQ2dpRU1BZ0t4Q0FBQUFBQUVBQUFBQW9JaERBSUNzUWdNQUFBQURBQUFBQUFDSVF3QUFnMElBQUlaREFBQmdRZ0JnZzBNQUFGOUNBQUFBQUFFQUFBQUFZSU5EQUFCZlFnTUFBQUFEQUFBQUFNQ0FRd0FBWGtJQUFIMURBQUNIUWdDQWZrTUFnSzFDQUFBQUFBRUFBQUFBZ0g1REFJQ3RRZ01BQUFBREFBQUFBQUNBUXdBQTFFSUFnSVZEQUFEL1FnQ0FqVU1Bd0JKREFBQUFBQUVBQUFBQWdJMURBTUFTUXdNQUFBQURBQUFBQUlDVlF3QUFKa01BQUoxREFJQXZRd0Rnb2tNQVFDOURBQUFBQUFFQUFBQUE0S0pEQUVBdlF3TUFBQUFEQUFBQUFNQ29Rd0FBTDBNQVFLeERBQUFpUXdDQXJFTUF3QXhEQUFBQUFBRUFBQUFBZ0t4REFNQU1Rd01BQUFBREFBQUFBTUNzUXdBQTcwSUFRS3BEQUFEUFFnQWdwa01BQU1SQ0FBQUFBQUVBQUFBQUlLWkRBQURFUWdNQUFBQURBQUFBQUFDaVF3QUF1VUlBZ0o1REFBQzhRZ0JBbmtNQWdNNUNBQUFBQUFFQUFBQUFRSjVEQUlET1FnTUFBQUFEQUFBQUFBQ2VRd0FBNFVJQVFLTkRBQUQxUWdEQXEwTUFnQUpEQUFBQUFBRUFBQUFBd0t0REFJQUNRd01BQUFBREFBQUFBRUMwUXdDQUNrTUF3THhEQUlBT1F3QkF3ME1BQUE5REFBQUFBQUVBQUFBQVFNTkRBQUFQUXdNQUFBQURBQUFBQU1ESlF3Q0FEME1BZ001REFJQUpRd0RnMFVNQUFQcENBQUFBQUFFQUFBQUE0TkZEQUFENlFnTUFBQUFEQUFBQUFFRFZRd0FBNFVJQVFOWkRBQUROUWdDZzFrTUFnTWxDQUFBQUFBRUFBQUFBb05aREFJREpRZ01BQUFBREFBQUFBQURYUXdBQXhrSUFRTmREQUFEVlFnRGcya01BZ08xQ0FBQUFBQUVBQUFBQTROcERBSUR0UWdNQUFBQURBQUFBQUlEZVF3QUFBME1Bd09WREFBQU1Rd0JnNzBNQWdBMURBQUFBQUFFQUFBQUFZTzlEQUlBTlF3TUFBQUFEQUFBQUFBRDVRd0FBRDBNQUFBRkVBQUFGUXdDUUJFUUFBT0pDQUFBQUFBRUFBQUFBa0FSRUFBRGlRZ01BQUFBREFBQUFBQ0FJUkFBQXVrSUFnQXBFQUFDTVFnQndDMFFBQUZkQ2dBWFNMaTh3TVZva1kyeGhjM051WVcxbFdDUmpiR0Z6YzJWelhVNVRUWFYwWVdKc1pVUmhkR0dqTWpNMFhVNVRUWFYwWVdKc1pVUmhkR0ZXVGxORVlYUmhXRTVUVDJKcVpXTjAwaTR2TmpkY1ZVbENaWHBwWlhKUVlYUm9vamcwWEZWSlFtVjZhV1Z5VUdGMGFOSXVMem83VjA1VFFYSnlZWG1pT2pUU0RRNDlFcUNBQndBSUFCRUFHZ0FrQUNrQU1nQTNBRWtBVEFCUkFGTUFYUUJqQUdnQWN3QjZBSDBBZndDQkFJTUFpQUNLQUl3QWpnQ2pBTUlBNkFFRUFTQUJQd0ZkQVhnQmtnRzNBYmtCdXdIQUFjSUJ4d0hNQWRFQjBnSFhBZDhGY3dWMUJYb0ZoUVdPQlp3Rm9BV3VCYlVGdmdYREJkQUYwd1hnQmVVRjdRWHdCZlVGOWdBQUFBQUFBQUlCQUFBQUFBQUFBRDhBQUFBQUFBQUFBQUFBQUFBQUFBWDT/4RKyaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/PiA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA2LjAuMCI+IDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+IDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIiB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIgZXhpZjpQaXhlbFlEaW1lbnNpb249IjIyNiIgZXhpZjpVc2VyQ29tbWVudD0iWW5Cc2FYTjBNRERVQVFJREJBVUdCd3BZSkhabGNuTnBiMjVaSkdGeVkyaHBkbVZ5VkNSMGIzQllKRzlpYW1WamRITVNBQUdHb0Y4UUQwNVRTMlY1WldSQmNtTm9hWFpsY3RFSUNWUnliMjkwZ0FHcEN3d1RGeWt0TlRrOFZTUnVkV3hzMGcwT0R4SmFUbE11YjJKcVpXTjBjMVlrWTJ4aGMzT2lFQkdBQW9BSWdBZlNEUTRVRXFFVmdBT0FCOW9PR0JrYUd4d2RIaDhnSVNJaUl5UWxJaVluS0Y4UUhGVkpRbVY2YVdWeVVHRjBhRXhwYm1WS2IybHVVM1I1YkdWTFpYbGZFQ05WU1VKbGVtbGxjbEJoZEdoTWFXNWxSR0Z6YUZCaGRIUmxjbTVEYjNWdWRFdGxlVjhRR1ZWSlFtVjZhV1Z5VUdGMGFFMXBkR1Z5VEdsdGFYUkxaWGxmRUJsVlNVSmxlbWxsY2xCaGRHaERSMUJoZEdoRVlYUmhTMlY1WHhBY1ZVbENaWHBwWlhKUVlYUm9UR2x1WlVSaGMyaFFhR0Z6WlV0bGVWOFFHMVZKUW1WNmFXVnlVR0YwYUV4cGJtVkRZWEJUZEhsc1pVdGxlVjhRR0ZWSlFtVjZhV1Z5VUdGMGFFeHBibVZYYVdSMGFFdGxlVjhRRjFWSlFtVjZhV1Z5VUdGMGFFWnNZWFJ1WlhOelMyVjVYeEFpVlVsQ1pYcHBaWEpRWVhSb1ZYTmxjMFYyWlc1UFpHUkdhV3hzVW5Wc1pVdGxlWUFHRUFBaVFTQUFBSUFFSWdBQUFBQWlRQUFBQUNJL0dabWFDTklxRGlzc1YwNVRMbVJoZEdGUEVRT1FBQUFBQUFFQUFBQUFBRjlEQUFDRVFnTUFBQUFEQUFBQUFJQmZRd0FBcFVJQWdHRkRBQURuUWdDQWFFTUF3QTFEQUFBQUFBRUFBQUFBZ0doREFNQU5Rd01BQUFBREFBQUFBSUJ2UXdBQUtFTUFnSGxEQUlBNlF3RGdnRU1Bd0Q5REFBQUFBQUVBQUFBQTRJQkRBTUEvUXdNQUFBQURBQUFBQUFDRlF3QUFSVU1Bd0lkREFBQTdRd0NBaUVNQUFDSkRBQUFBQUFFQUFBQUFnSWhEQUFBaVF3TUFBQUFEQUFBQUFFQ0pRd0FBQ1VNQVFJbERBQURXUWdDZ2lFTUFnS3hDQUFBQUFBRUFBQUFBb0loREFJQ3NRZ01BQUFBREFBQUFBQUNJUXdBQWcwSUFBSVpEQUFCZ1FnQmdnME1BQUY5Q0FBQUFBQUVBQUFBQVlJTkRBQUJmUWdNQUFBQURBQUFBQU1DQVF3QUFYa0lBQUgxREFBQ0hRZ0NBZmtNQWdLMUNBQUFBQUFFQUFBQUFnSDVEQUlDdFFnTUFBQUFEQUFBQUFBQ0FRd0FBMUVJQWdJVkRBQUQvUWdDQWpVTUF3QkpEQUFBQUFBRUFBQUFBZ0kxREFNQVNRd01BQUFBREFBQUFBSUNWUXdBQUprTUFBSjFEQUlBdlF3RGdva01BUUM5REFBQUFBQUVBQUFBQTRLSkRBRUF2UXdNQUFBQURBQUFBQU1Db1F3QUFMME1BUUt4REFBQWlRd0NBckVNQXdBeERBQUFBQUFFQUFBQUFnS3hEQU1BTVF3TUFBQUFEQUFBQUFNQ3NRd0FBNzBJQVFLcERBQURQUWdBZ3BrTUFBTVJDQUFBQUFBRUFBQUFBSUtaREFBREVRZ01BQUFBREFBQUFBQUNpUXdBQXVVSUFnSjVEQUFDOFFnQkFua01BZ001Q0FBQUFBQUVBQUFBQVFKNURBSURPUWdNQUFBQURBQUFBQUFDZVF3QUE0VUlBUUtOREFBRDFRZ0RBcTBNQWdBSkRBQUFBQUFFQUFBQUF3S3REQUlBQ1F3TUFBQUFEQUFBQUFFQzBRd0NBQ2tNQXdMeERBSUFPUXdCQXcwTUFBQTlEQUFBQUFBRUFBQUFBUU1OREFBQVBRd01BQUFBREFBQUFBTURKUXdDQUQwTUFnTTVEQUlBSlF3RGcwVU1BQVBwQ0FBQUFBQUVBQUFBQTRORkRBQUQ2UWdNQUFBQURBQUFBQUVEVlF3QUE0VUlBUU5aREFBRE5RZ0NnMWtNQWdNbENBQUFBQUFFQUFBQUFvTlpEQUlESlFnTUFBQUFEQUFBQUFBRFhRd0FBeGtJQVFOZERBQURWUWdEZzJrTUFnTzFDQUFBQUFBRUFBQUFBNE5wREFJRHRRZ01BQUFBREFBQUFBSURlUXdBQUEwTUF3T1ZEQUFBTVF3Qmc3ME1BZ0ExREFBQUFBQUVBQUFBQVlPOURBSUFOUXdNQUFBQURBQUFBQUFENVF3QUFEME1BQUFGRUFBQUZRd0NRQkVRQUFPSkNBQUFBQUFFQUFBQUFrQVJFQUFEaVFnTUFBQUFEQUFBQUFDQUlSQUFBdWtJQWdBcEVBQUNNUWdCd0MwUUFBRmRDZ0FYU0xpOHdNVm9rWTJ4aGMzTnVZVzFsV0NSamJHRnpjMlZ6WFU1VFRYVjBZV0pzWlVSaGRHR2pNak0wWFU1VFRYVjBZV0pzWlVSaGRHRldUbE5FWVhSaFdFNVRUMkpxWldOMDBpNHZOamRjVlVsQ1pYcHBaWEpRWVhSb29qZzBYRlZKUW1WNmFXVnlVR0YwYU5JdUx6bzdWMDVUUVhKeVlYbWlPalRTRFE0OUVxQ0FCd0FJQUJFQUdnQWtBQ2tBTWdBM0FFa0FUQUJSQUZNQVhRQmpBR2dBY3dCNkFIMEFmd0NCQUlNQWlBQ0tBSXdBamdDakFNSUE2QUVFQVNBQlB3RmRBWGdCa2dHM0Fia0J1d0hBQWNJQnh3SE1BZEVCMGdIWEFkOEZjd1YxQlhvRmhRV09CWndGb0FXdUJiVUZ2Z1hEQmRBRjB3WGdCZVVGN1FYd0JmVUY5Z0FBQUFBQUFBSUJBQUFBQUFBQUFEOEFBQUFBQUFBQUFBQUFBQUFBQUFYNCIgZXhpZjpDb2xvclNwYWNlPSIxIiBleGlmOlBpeGVsWERpbWVuc2lvbj0iNjM0IiB0aWZmOk9yaWVudGF0aW9uPSIxIi8+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPD94cGFja2V0IGVuZD0idyI/PgD/wAARCADiAnoDAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9sAQwABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB/9sAQwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB/90ABABQ/9oADAMBAAIRAxEAPwD+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9D+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9H+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9L+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9P+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9T+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/9X+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA8I+Of7Uf7Nf7MOmaNrP7Rvx9+DvwK0vxFetp3h+9+LXxG8JeAINdvU8vzrbRz4n1bTTqctuJonulsln+yxuslwYo2D0Aer+FPFvhXx34c0fxh4H8TeH/ABl4R8RWMWp+H/FPhTWdO8ReHNd024yYNQ0fXNIubzTNTsZgCYruyup7eTBKSHFAHQUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAHzj8XP2sPgb8Dfi9+zn8CfiR4suNG+J/7VviXxh4S+B/hu00DXdak8Va14C8OJ4r8Upc3OjaffW2g2Ol6JLHdTarrkthpil1iN0HO2gD6OoAKACgAoAKACgAoAKACgAoA/9b+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDmfGvjHw78PPBvi3x/4v1KHRvCfgbwzr3jDxRq9ydtvpXh3wzpV3rWtalOxwBDY6bZXNzKSeEiY8UAfzUf8Et/2MPh1/wAFObX4hf8ABXf/AIKH/CLwp8dfGH7WfiDxRa/spfB/40eHtN8c+Af2cf2PvD2t6p4c+G+geG/A/iGLUvDNv4r8dWtneeKvEXicafJeahbalaanYy2N34h8RNqAB0HwY8DW3/BF/wD4Kj/Df9ln4eXWqaR/wTb/AOCnaeNLj4JfDq/1C+1Hwx+y9+2n4Ksl8Qa74H8ET3811LoXgH43+GpBLonh0zbJPGIt7HTYrez0OZ7sA/pdoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP569Mf/AIa3/wCDjLW9Rh26l8Of+CU/7F8Hh3zgDPa6d+0t+2Lefb7tI5A3kJdL8EdO+z3KjfPb3FsqPHEwV2AP6FKACgAoAKACgAoAKACgAoAKAP/X/v4oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD8rv+C2f7Rvxw/ZH/4Jd/tY/tG/s4eLIPA/xm+FnhjwPrfg/wAU3Ph3w74rh0r7b8WPAWg68z6B4r0vWdAv/tPhnVtZsh/aGmXS2zXIu7dY7qCCZAD9J/AuuP4m8E+DvEkjrJJ4g8K+HtckkVVRZH1bSLS/d1VQFVWa4LBVAUA4AAAFAHVUAFAH4sf8HDfxU1j4Vf8ABH79siTw1JKvir4oeE/CXwC8OQwStDNd3nx4+IfhP4WalaRyJlwZfDnifWywXlkRl43ZoA/UX9nj4S6L8A/gH8E/gd4dgittC+D3wm+Hnwx0mGCIQxLYeBvCWk+GrcrEoAQyR6asjjqXZixLFiwB+QP/AAcZ+BNZuv8Agm5rn7Rvgi2DfFT9hP43/Aj9sz4aX0e6O8sNW+EvxF0i38SPBdR4kghPgbxF4nnu0y0MyWqCaN9iFAD9sfh9410b4k+AvBHxF8OS/aPD3j7wh4a8a6FPx++0bxVo1lruly8Ej95Y30D8Ej5uCeDQB19ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAcN8TviL4T+D/w38f/ABY8eanFovgj4ZeC/E/j/wAX6vOyrFpnhnwhot7r+uXzliARbabp9zKFzlyoRcswoA/FP/g30+HvizV/2Tvij+3V8VNMm0/4wf8ABTL9of4lftea9Be/NfaL8NfEOr3GgfA/wisuOdG0bwBpdvrOgRK7xw2HijbGeW3AH7y0AFABQAUAFABQAUAFABQAUAf/0P7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/IT/gvpoX/CRf8Eb/APgoVp4G77P+z5rmu4xn/kV9Y0TxMT/wEaRuz2xntQB98fsk67/wlH7Kf7MviYNuHiL9nz4Ma6GBzu/tf4ceG7/dnnOftGc5/PNAH0HQAUAfgF/wcZf6f+x9+zJ4Qk+ax+IX/BSz9hjwZqcTcpPYXvxSk1SSKRf40MukQMV5yVB7ZUA/f2gD5J/b6+F9r8bP2G/2w/hHd24uo/iN+zH8c/CEURTeRfa38NfEllps0a4P7621GW1uYDjKzRRsMECgD5m/4Ig/Ey5+Lv8AwSO/4J8eNL25N5er+zL8PPB17dM2+S4vPhnYyfDW6lmY8tO8/hJ2nY4JlLkgE4oA/U+gAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPwC/4L1+O/E/xX+Hv7Nn/AASu+Eeq3Fl8Xv8Agpv8Z9J+F/iW80yT/iY+Cv2Wvh5c6f45/aP8fTpGHkjsbbwvZ2Xh+WKZUh1TTtX1uzid5omjoA/dLwH4I8MfDPwP4N+HHgnSrfQfBvgDwr4f8FeE9EtFCWuj+GvC2k2mh6HpdsgwFgsNMsbW1iAH3Ih05oA6ugAoAKACgAoAKACgAoAKACgD/9H+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPz6/4KyeEX8d/wDBMH/goR4ViQyT6n+xr+0a9tGBlpLvTvhR4p1W0jUDPzvc2MSp6MQeMZoAm/4JR+LV8d/8Ex/+CfXisP5jav8Asbfs4yTnO4rd23wm8K2V5ExJOXgu7aaF+fvRnpigD7/oAKAPwA/4ONz/AGd+xn+zj4yf5bX4df8ABSL9hzxtfSngQ2lj8VDpbys54jAk1eJS5KgbsZ5oA/f+gDP1bT4NX0vUtKuo1ltdT0+80+5ib7skF7bS200bf7Lxysp9jQB+Df8AwbM31wn/AASC+Bfgu8dnu/hT8Tv2nvhhPu+9GPDP7RvxNktYSP4fJsdQtY1Xsir6mgD99KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgBkkkcUbyyukUUSNJJJIypHHGilnd3YhURFBZmYhVUEkgAmgD+dP8A4JjmX/goX/wUT/bF/wCCturo1/8ABP4erqH7BH7AT3IaWy1H4bfDnXZb746/GnQg7eU1t8SPiG0un+H9Zt4Y7l9FXX9Bu3IsAlAH9F9ABQAUAFABQAUAFABQAUAFABQB/9L+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPGf2jfCn/Cefs9fHjwN5fnf8Jn8Gfih4U8rbu83/AISLwRrmkeXt/i3/AGzbt75x3oA/Mn/g3m8XL40/4IxfsC6n5nmSaV8IdQ8GTgk7oZvAPj7xh4KNu4OSrQLoKRlP4MbTjGKAP2coAKAPxK/4OLPhvqXxH/4I6ftjyaEsn/CRfDHw34F+OehTRIZGtbn4KfFDwZ8R9QuiowSkOgeH9YMhBXZGWckKrbgD9YvgZ8StM+M3wU+D/wAX9Gljn0j4qfC/wD8RtMmhkEsUlh428K6T4ltGSQEh1MGpJhs898EUAep0AfgB/wAG5X+g/seftNeFF+WPwJ/wUr/bl8IxRdoI7P4oRakIQOwB1VmxheWPHNAH7/0AFABQAUAcl488e+CPhb4N8S/ET4k+LvDngLwF4N0i717xZ4y8XazYeH/DXhzRbCMy3mqazrOpz21hp9lAgy89zPGm4qgJdkVgD8YrH/g5G/4IyX3iz/hFV/bI0y0gfUpNHt/HGpfCf44ab8MLvUoZGikt7b4k3vw3g8HtCjq3/Eyk1WPSig81b54Sr0Afsb8M/in8M/jR4K0T4kfCD4g+C/ij8PvElst3oHjX4f8AibR/F/hbWLcgEyafruhXl9p11sJCypFcM8EmYpUSQOigHe0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfiJ/wXA/aa+I3g74H/Dv9hj9mO+B/bL/AOCkvjC4/Zs+Di20zi68AfD/AFS0T/he/wAb9S+zut1YaF8OPh7e3m7Vonin03UtYtNYtTL/AGNcooB+m/7J/wCzX8O/2PP2bfgt+zD8KLL7H4C+Cfw/0HwLojvFHFd6tJplsDrHiXVBF8j634r1ybUvEuuzqW+0axqt9Pn96aAPoSgAoAKACgAoAKACgAoAKACgAoA//9P+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAGSRpLHJFIoeOVGjdGAKsjqVZSDkEMpIIIwR1zQB+Af8AwbWu2g/8E4td+DTsRL+zj+2R+2T8D5IGbLWh0D44+JPE62pB+ZRHH4vQqrYIVhgBQooA/f8AoAKAPMvjX8LfD/xy+DfxY+CviuNZfDHxd+Gvjn4ZeIo3QSK2ieO/DGp+F9U/dnAYiy1SZlGR8wGCp5oA/Ib/AIN4fitr/jL/AIJnfDv4K+P5dnxe/Yi+IHxT/Yk+LOmPIWn0jxH8APF17oXh2yeN8TRxJ8OrvwWsJlRd2yRY9yIHYA/cagD+fv8A4N9QbLwJ/wAFRfDnIXwx/wAFm/28NNSM/wDLJZtb8E6hs9v+PvOML1zjmgD+gSgAoAKACgD+d7/grZ4Wi/bP/wCCgX/BL3/gmL4za4uf2cfiJqnxl/a9/ai8JR3lzaWnxP8ACP7N+jaVJ8Mvhvry2ckUmoeEdd+IGsPJ4n0uaQQ3MVvp13Fsv9Os7iAA/dyT4P8Awll8BxfCuX4XfDqX4YwaTHoMPw5k8E+Gn8BxaHDGIYdGi8INpjeHk0qKFVij05NPFmkahFgCAKoB+AX7SX/BK/4n/sB+IfEn7cn/AARL834Y+O9Fnk8YfHb/AIJ5Lf30n7L/AO1r4U02IT6/o3g/wU80tr8KfjD/AGXBOPBeq+Do7LT571LXR9MsdGN3dpq4B+w/7C37aXwi/wCCgH7Mnw5/ae+DM97B4c8bWdxZ6/4T1ry4vFfw28e6HN/Z/jT4b+M7JMGx8TeEdaSewu0ZEiv7T7DrVhv0vVLGecA+u6ACgAoAKACgAoAKACgAoAKAPxC/4KZ/8Fo/h9/wTh/a2/YP/Zm8T+BofFtl+1T4vkg+K/jFtel0s/Az4aaj4q8O/Drwx8Qbixj0+7h1Oz1Dxz4imF4L660+2g0fwvrUcUr6hdWKqAft7QAUAFABQAUAFABQAUAFABQAUAFAHOeMPF/hj4f+EvE/jvxtrum+F/Bvgvw/rHivxX4k1m5Sz0nQPDnh/T7jVdb1nU7uQiO2sNM021uby7nY4ighdznFAH8+3/BJzwt4q/b9/ak+Nf8AwW3+Muh6jpPhPx9pWqfs6f8ABODwF4itri3vPAn7J3hbXbyLXvi7Npl2Mab4q+PHiiG/1Ezoi3lroP8Aatnb3d74c1rTHYA/osoAKACgAoAKACgAoAKACgAoAKACgD//1P7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP5+v+CJqj4fftH/APBb79nYHy4vAP8AwU+8c/GPS7InH2HQf2lfA/hvxtpcESfw2xbRbuaI4+ZpZGLNkBQD+gWgAoAKAP53PgzL/wAMHf8ABe39oL4H35Ok/BH/AIK1/CbT/wBp74QGRo49Jtv2rfgLp7+H/jp4T04N5QTWPGfgeVPiXrL/AL9rqZdLt0xIQlAH9EdAH8/n/BB0/ZvFP/BaTSui2f8AwWw/bHvFX+6NW0z4aXWAOMDKnA+vXk0Af0B0AFABQAUAfz0f8FbtbH7If7fP/BKj/gpfrzta/BLwB4/+Jv7Gf7S2uPGWsPBPgX9qfRLHT/h38QtbuV40vwx4T+IeiiXxDqk+YIkvdOtQDcXkKsAf0KRyRyxpLE6SRSoskckbB45I3G5HR1yro6kMrKcMDkZBoAfQB/OZ8MtOT/gmr/wXH8VfBfSE/sL9lP8A4LCeDPFfxw+H+iRq1t4c8FftzfBiyjvPi/puiwhBZaefi38Pp4vGOqgSRSar4kbSNPsoBDpscVAH9GdABQAUAFABQAUAFABQAUAFAH8hMP7JGkf8Fr/2gP8Agu78X9W+y3ngm18C6R/wTC/Y78VXimSx0fxr+z5LafFnxx400i+cMi6XB+0lb+CtXg1LSz/pelnU7X7SAZkYA/ar/gjR+2Fq37aH7APwd8cePBcWXx4+Fsep/s7ftMeHdSIXXfDvx9+CM6eCvHcWvW2+RrTUfERstO8a/Z3bMVt4ngjOGRkUA/UygAoAKACgAoAKACgAoAKACgAoA/nD/wCCm/jnxd/wUr/at8Lf8EUf2fvEOoaV8MbKy8NfGP8A4Kl/F3w1cyxSeAPgPHe2ureEP2b9K1e3LR2nxE+OV5BZPqNpu+1ad4Ve0up7XUNEl8VWduAf0LeCvBnhX4c+D/Cvw/8AAug6b4W8FeB/Dui+EvCPhnRrdbTSfD/hrw7p1vpOiaNptqny29jpum2ltZ2sQJ2QwopZiNzAHTUAFABQAUAFABQAUAFABQAUAFABQB//1f7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP5+P2Xdnwj/AODiP/gpv8Ngfslp+1H+xx+yH+1Dptmfkhur34Uz6t8B9dv7VOFeWa5u0N/IgLNIsZlOVSgD+gegAoAKAPxb/wCC5f7MvxG+L37J2g/tI/s7Wjt+1v8A8E+fiPof7Yf7PU1pHK9/r1x8Nz9t+JnwzKW5Fxf6Z8Rfh7BqtlPoEYdfEGs6V4e02aN45CtAH6J/sf8A7T/w6/bR/Zj+CX7Uvwpu1ufA/wAa/AOi+M9NtzMk91oWoXcJt/EfhPVHjAQa34P8SW2reFtbjUBY9W0i8RNyBWoA/Iz/AIIY/J8Wf+C3kXZf+CyP7Scnt++8LfDts9TySOf1JwKAP6BKACgAoAKAPFv2i/2fPhR+1Z8Dvid+zr8cPDFv4w+FXxc8J6l4P8Y6FORHLLYX6K9vqGmXflySaZr2h6hDZ634d1m3X7Xo2u6dp+q2jLc2kLKAfg5+xT+118Vf+CXfxb8Hf8ErP+Cmfi+6vvA93OPDP/BO/wDb18UH7H4H+PPw7smitfDXwO+L/iO4kOn+EPjt4E0+Sw8PWX9r3UNr4msorC1+0tNL4e1fxiAf0mUAfgH/AMHFmgal4M/Y2+En7b/hG0mf4gf8E6f2uP2eP2p9Iu7DK6nN4OsvH2meAviT4dWReW0fW/D3jCO6160c+Td2eiqJlYRigD959C1rTfEuiaN4i0W6S90fX9K07WtJvYjmK703VbSK+sbqM8ZS4tZ4pUOOVcdKANWgAoAKACgAoAKACgAoA/N3/grV+2dJ+wj+wZ8cPjh4fWW++LN/o9v8K/2fPDdlCbvVvFfx/wDipN/wh/wu0nSNORJJdTuLHXdQXxPe2MKNLLonh/VXQEp8oBt/8Er/ANjeP9gv9gz9nj9m6+Zbvx14a8HJ4m+MOtmY3dz4j+NXxAup/GnxU1i61B5JptSz4x1rU9OsL2eV5n0fTtMjYgRKqgH5f+Mrof8ABJb/AILE23xKu2j0L9hP/gsRrejeEfHl85Fp4X+Cv/BQXw1YyweFfEmoSu4sdG0v9onQWmsNQuysTar40/tHWNUuINP8PRtQB/SPQAUAFABQAUAFABQAUAFABQB+Uf8AwVT/AOCid9+xb8PPBfwq+A/hmP4xft7/ALVGrz/DL9j74CWAjvb7W/GN7H9nvfib4ytRIo0r4VfDKKYa/wCKtY1GSz066a2i0mS/sLSXVNX0YA7T/gl3/wAE/bH9gH9n+90DxZ4sn+LX7T3xt8T3fxl/a7+PurM9zr3xe+OPigPea/e/brmKO8HhHwxJdXGg+CdLdYIbXS459TaxtNU1zVg4B+lFABQAUAFABQAUAFABQAUAFABQAUAFAH//1v7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP59v2xT/wAKT/4L+/8ABKD41Mv2TR/2nv2dv2t/2NPEmpjCRNeeELHS/jp4D0q8fgZ1LxFLcR6ejFmluoikaggtQB/QTQAUAFACMqspVgGVgVZWAKspGCCDkEEZBBGCODmgD+bb9jec/wDBJz/gp38UP+CcniQnRf2N/wBvzXPGP7UX/BPnVbhvI8O/D/4yv5V9+0N+y5ZTTSeRp8U07Q+Nvh/o0JitLfTnsdPtEvNd8UXCqAejf8EM/wB58XP+C3s4GEf/AILHftHxKO2638K/DxJMf8CbkdvxoA/oEoAKACgAoAKAPnz9qL9lb4A/tnfBfxZ+z9+0t8NfD/xT+FfjK3VNT8P67AwnsNQgDnTfEXhzV7Z4NW8M+KdGmdrjRvEeh3ljq2nTF/s90kcsySgH4P2Ev/BS/wD4IkkaPPo/xM/4Ko/8Ev8ARHij0fUtHWHWP29f2SfB1rE+NP1DS2kt4P2h/hv4bs0EVrcWht/EOm6fAgc+EdC0yOzuwD60/aD/AGof2QP+Csf/AASc/bnh/Zd+MnhD4taV4j/ZO+NlvqPh+yuH07x74C8W2nw413W/D2n+Pfh9q8Vl4u8H6zp/iPT9Pkig1zSLSG7ntPN025vbQpcsAfTf/BIv4oXnxm/4JffsCfEbUp2utW139lH4K2utXTtve61zw54I0nwvrdzI3OZJ9W0W8lkzyHdgcEEUAfopQAUAFABQAUAFABQAUAfzd61dx/8ABV7/AILL6B4a01v7f/Yh/wCCNmsf8JR4sv4ytx4W+K//AAUR8R2rQeHPD8T4Ntq8X7OXh9ZtSupIpGm0Dxwl9pt5C9l4gtncA/pEoA+VP22P2PPhD+3n+zP8UP2Xfjbp01z4L+JGjC3t9Z08RJ4h8EeK9NmTUvCHj/wldyA/YPFHg7X7ey1rSpwfJna3l06+juNMvr61nAPy2/4Jo/t2fFz4VfFI/wDBJz/gpfq1von7avwp0nyPgJ8bdSMtj4J/b0+BukK9p4Y+JPgbWtRcR3vxX0/SbRbb4jeEJLiXXri/sb7Vgt1qVr4nt9NAP30oAKACgAoAKACgAoAKAPzU/wCCj3/BTH4Vf8E/PBfhnSToWr/G39qn40Xb+F/2X/2Tfh4H1P4pfGvxxdP9jsFg02yhvLvw/wCBdNvnjfxT43v7RtP0y0jngsI9S1g2+mzgHgv/AATR/wCCdfxP+HHxD8cf8FCP+CgGv6J8WP8AgpD+0FpMVjrl5pmL34f/ALK3wql/0jR/2cvgVBNLdQaZpGjQukHjHxNYTSXHifU0uI11DUbd9T1zxOAftLQAUAFABQAUAFABQAUAFABQAUAFABQAUAf/1/7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP5+P+Dh6KX4ZfAD9jv9tyxWSK5/YO/4KEfsv/HHxHfRqSY/hfr/AItb4YfEKwmcAmKz1OLxhokd1IxEapADJkBaAP6AoJ4bmCG5t5EmguIo54Jo2DRywyoJIpI2GQyOjKysDgqQRnIoAloAKACgD83/APgqb+wVaf8ABQP9lnV/hx4d1/8A4V5+0D8NPEOj/Gv9lL4yWjNa6z8Jf2hPh9I+q+BfEVpqUMb3dnpOqXSv4c8TiBZW/sTVLi+gt5tS07TXgAPyN/4NdviJ8RviF8Of+CnmqfH+z0Twt+0/qP8AwU1+MPif9oD4cafNbQX3g3x7rXgj4e6d4hE2ixXV3NpukXvjPw74ysdHl82WwuJ9E1W10+6uU02VkAP6kqACgAoAKACgAoAKAPxa/bs/4IifsfftU6t4q+O/gOHxt+yJ+1lJ4f8AEKRftJfsra/L8LvGfiM6hpskV/pvxM0LSRF4V+Jmj67Ag0/xAniHTP7e1TTJZdP/AOEit7eXagB+Fv8AwRS/bO/4Ktfss/8ABMb9lrxxL+xHov7dn7Cn9g+PtM8GX/7LniT+z/2vvhFovhL4p+PfDet6b4t+E3ikw6V8W4Ydd0LWbjw+ngSe11BNKvLCHWdTSaHy1AP6Hv2VP+C1v/BOT9rjWP8AhB/CHx/0n4WfGi2uv7N1n9n39o6xufgL8bNE1oMiy6FL4N+IP9lx65qsLyIssHg/VPEcaMwBmJ4UA/VhWV1VkYMrAMrKQVZSMhlIyCCDkEHBHIzmgBaACgAoAKACgD8Nv+Cn3/BQz4j6V4y0b/gmp/wTtaz+IX/BR/4/6W9lLqWnSfbfCn7Gfwp1NIoPEn7RHxn1W1S5tvDd5oekXv2zwD4cvVbVNT1ebS9T/s2+SbQdD8VgH3x/wT+/Yg+F/wDwT0/Zb+Hv7NHwvmvdbj8ORXev+P8A4g63+88V/Fn4q+JpE1Hx/wDE/wAXXbyTz3Wt+KtaMk0cc9zdnStHg0nQbe5ls9KtioB9o0AFAHw1+3v/AME9f2d/+Cifwig+GPxy0jVdN17wvqkfiv4P/GbwJqDeGfjH8DPiDZNFNpXjr4X+NbWM6homq2l1bWkt7YO02j61FawQ6pY3D21lNagH5I6D+3x+3Z/wSQubT4Xf8FZfBHib9pv9k3TJ7bSPAX/BUf4BeD9R1+50bQUjMVhF+2H8IdGhvtf8I65awxxRan8RPD66jp2qTiMLF4u1a51DVkAP3q+A37RvwF/aj+H+m/FP9nX4vfD74z/D7VUja18U/DzxPpniTT4pZIxL9g1MWFxLc6Lq0KnF3o2sW9hq1jIGhvLKCZXjQA9poAKACgAoAzdZ1nR/Duk6jr3iDVdN0LQ9Hs7jUdW1nWb610zSdL0+0jaa6v8AUdRvZYLOys7aFHluLq5mighjVpJJFRS1AH4C/Gv/AILM+L/2i/HniH9lX/gi38KrP9s/48WVxJoXjn9p3V/tmnfsNfs2TTqqvrfjb4pQGOH4m67YRSG+03wd4CmvIdZEZew1TWp7a40GcA+nP+CfX/BKfwv+yl428T/tVftEfEvWf2wP+ChvxX077N8VP2q/iHaKs+haZdLmX4bfAvws7S6f8Kfhfpin+zrTS9Eitr7VLGJIr17PSRZeHtLAP1woAKACgAoAKACgAoAKACgAoAKACgAoAKACgD//0P7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPhz/gph+ziP2uf+Cf37YH7OUVt9r1b4o/AT4haP4Vh8sTY8d6dolx4g+H8wjKtua18b6P4ful2qXDQgx4cKaAPNP+COX7SJ/ay/4JifsW/Gu7vPtviLVfgh4X8H+OZWctcD4ifCxJvhf49+1q5MsN1N4s8IatdSQz/vkW4QvktuYA/S6gAoAKACgD+An9l7wX+0L+yn8UP+Cin/AAWr/ZbsvFPxNHwm/wCCsP7c3wk/bi/Zs0y7lnh+M37Gen+OfDfiW58aeCdPLC3j+JnwM1vW/EfjPT5fKzeaPLevNPFpmna1pmvAH9zPwE+O/wAKv2nPg38Ovj78EfF+m+O/hX8VPDGn+LfBnifS5A0F9pmoId0F1Af32navpd3HcaVrmj3ixahous2V9pWowQX1ncQIAeu0AFABQAUAFABQBjeI7mKy8Pa9eTtsgtNG1S5mf+5FBYzyyN2+6ik9e3agD8L/APg2Rtpbf/giT+xi8qlTej4+6kno0F/+0x8Y7qBx04eGRHGOPm75zQB+kn7VP/BPn9if9tzSG0j9qr9mX4SfGdhbta2niHxR4Vs4vHOkQGJodmgfEPRxpvjrw/tjchToniGxxhT/AALtAPywH/BD74yfs4Zvf+CZn/BUr9sH9lGxsSs2jfBL4x6ppv7XP7OFmIT8mkab4D+KTQ6x4f024iAt5ruDX9X1GBf38LGYJtAJx8Vf+Djn9nAtB44/Zf8A2Ev+CiXhaw/1eufAT4u+If2XPitqVmud1xquhfFy01DwCNUCKZDY+HkNtM7LBC4IL0ATj/guh8S/hsRa/tU/8Ec/+CpPwVuotv27W/h58GNE/aP+Hln1Dt/wnHw98RWKXCqwJBh0Yhox5mVztoAsL/wcxf8ABK3SyI/iL4u/aO+D1yOJbT4m/sh/tE6VcQS97eYaJ4A8QRLMrZRgsrpv4EmBlgCOf/g5V/4JweIg1r8BtH/bB/ao8QMCtl4X+AP7Hnxx1zWL+5I/c21v/wAJn4Y8D2IeZ8IJHvVjXO5jgEUAchq/xv8A+C33/BRlG8Ifs/fs7Wf/AASM/Z413/RNf/aL/afu9H+IH7Xl94fuomW7/wCFW/ALQJzo/wAOvEjW84iS7+IN881jNm80TXrK/tUdgD9NP2A/+Cbv7On/AATu8Ba94f8AhDZ+IvF/xL+Iuor4k+OX7RHxS1d/GHxy+OvjSR5bi78S/EPxtdxrdXSG9uby403QLBbPQtJa7upreybUb3UtRvwD79oAKACgAoAr3dpa39rc2N9bW97ZXtvNaXlndwx3Nrd2tzG0NxbXNvMrxT288LvFNDKjxyxsyOrKxFAH4kfG/wD4IH/sa+LviBqXxz/ZV8QfGL/gnL+0TqMrXdz8Vv2JPHN38JtM1u7M8lyyeMPhRbpc/DPX9NuZp55NTsbLw/oM+qNM5vdRkZmNAHl8Xwn/AODjH9mPZa/Dz9pf9hr/AIKMeB9PDQwWn7R3w18Vfs1fGy4sYji0ii8Q/CW4v/AF/qPlfJdan4gdnuZlSZ0+eWgC4n/BSr/gsT8P2Nh8Zf8Agg94/wDEM0GVk8Rfs7ftkfA74jaLqABx9pstEv8AT9M1y0SQ5K2t7M08S/fkJNAEp/4K8/t+X4+zeHv+CCP7dt1qh/drD4j+IfwX8J6V5/ZW1u91G5t1t/W6NuUHUqcfKAUZP2i/+DiP9oNfsPwp/wCCf37Hf7C2j6iwhTxr+1b+0ldfHrxJpdmw/eajb+CfgNp1nAupopJtdO1gz2gnVftbSQFtwBXsf+CHfxC/af1bTvFn/BXL9vf45ftzw2t5Fqsf7NngPP7NH7IWnXsdxFcQW198Nvhtf2mt+OUsBAkFvqus61o93ewtMmp2lwk0iOAfuZ8Jfg78KPgL4C0H4W/BP4b+CfhP8OPDFslpoHgj4feGtJ8J+GdLhVERjbaRotrZ2guJxGr3d28T3d7NuuLuead3kcA9IoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//0f7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD+en/AIIwsf2Zv2p/+CsH/BNDUibHT/gj+1O37VPwH06dBCr/AAB/a+0qLxvZaXoSLiO40jwL4rsrzSb6aBdtvquuPBMscrbKAP6FqACgAoAKAP5+/wDg3et4NS/Zh/bZ1m4hjuIfGn/BVL9vLW50mjSWK7gu/Huk6e6yo4KTRSLZvG6uCrqWRgV4oA+ffEtnrn/Bvf8AtPat8RdCs9X1L/gi9+118SUvfiV4b0y0vNTh/wCCdf7Q/jS8gtf+E70PTrSKeWx/Zw+JepvBBrem2cK2vhHVGt7exigubLQtM8ZgH9Oei61o/iTRtJ8ReHdV07XfD+v6ZYa1oeuaPe22p6RrOj6raxX2marpWo2ck1nqGnajZTwXlje2ksttd200U8EjxOj0AadABQAUAFABQB85ftieO7f4XfskftR/Eq6uFtLf4f8A7O/xp8aS3LMEEK+GPhv4k1nzNxwFKmyBBJxnGcUAfDH/AAQU8Cy/Dv8A4I6f8E9vD81u1tLffs8eHPGzRMpRivxK1DVviLHKykA5ni8UpNyOQ4POaAP10oAKACgAoAY8ccg2yIki+jqrj8myP89uDQAJHHENscaRr/dRVQfkoA/T8+aAH0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//9L+/igAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/nh/wCCg7j9i/8A4LA/8E1v2/oCNL+GX7Tdp4j/AOCZP7SupKz21jFc/EG8m8f/ALM+t6tKFNoPJ+JNjqen3mp3/ltaaTZQ2sVwEkELAH9D1ABQAUAISFBYnAAJJ9AOSfwFAH4A/wDBtWf7R/4Jtal4zHzL8R/2wf2yvG6zf8/C33x58V6V5wP8WTo5TdlvuYzxQB+53xD+Hvgf4s+BfFvwy+JnhXQ/HPw+8eeH9U8K+MvB/iXT4NU0HxH4d1q0lsdU0nVLC5Vorm0u7WZ43UgMpIkjeOVEegD+aDwJ48+KH/BvJ8VNH+Bnxz1jxf8AFP8A4IvfFjxgmk/s8/tCavJf+J/Fn/BPjxh4o1CRrP4J/Gq+C3Go3/wD1HUbkxeBfHEwf/hHPM+zXWJBe2jgH9P2jazo/iPSNK8QeHtV03XdB13TrLWNE1vRr611PSNY0jUraK807VNK1KylnstQ07ULOaG7sr60nmtru2linglkidHYA0qACgAoAKAPxC/4OIfinqngT/glb8dPhz4R3XHxN/ax174a/sffCvR4pDHP4g8XftAeN9J8KX+kQbcySPL4GHjG5aKNWaWO1eMrhs0Afrb8EfhjpXwT+DHwj+DehCIaJ8Jvhl4D+GmkCGMRRf2Z4F8LaV4YsTHEOI0NtpcRVB90HHagD1CgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP/0/7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD85/+Csn7HEv7d/7AP7RH7POif6N8SNT8JL43+CmsRSvbXug/G74aXtv45+F+oWF/EyTadJdeKNEs9Cvb2BhLHpGsaki5EjKwBZ/4JT/tlxft5/sFfs+ftE3+LX4g6v4TXwb8atBkQ2994Y+OHw7uJPBvxT0bUbB44p9MlfxVpF9rFhZXMMU40TVtKuGjCTpQB+h9ABQByHxB8QR+E/AXjfxTMypD4a8IeJfEErvwiR6No17qLs5PAVVtiWz2BoA/Fr/g2q8PS6B/wRW/YtluUZbrxRpnxi8c3LP/AKyWTxn8fvin4hSZzgFjJBfQlGOS0ew5xigD91KAOM+Inw68CfFzwL4r+GXxP8I+H/H3w98daHf+GvGHg3xXpdprXh3xHoOpwtb32l6tpl7FNbXVrPExysiFo3WOaJkmRHUA/m2n8Bftef8ABAfWrzXPgj4d+JX7a/8AwR3u9Su9V8SfA6wurrxh+05+wJY3tzLe6rrXwlN/Mb34q/AXTnmnvbzwlc3g1bw3arLdzXGn+RrXirxIAfvp+y9+1j+zv+2h8I/D3xz/AGZPit4U+Lnw18RwqbfW/DN8JbrSb8Ir3OgeKdEuBBrXhPxNpxYR6l4d8RWGm6xZOVM1osbxu4B9EUAFABQB/OP8TdXi/wCCnH/BbD4P/B7wo39v/sqf8Ed5Ln44/HLxBADceGfFn7c3jbTp9F+D/wANLe7VJrG+1j4LaLHf+M9Rkt5PP0XX08Q+HdVjtrn7OJQD+jigAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD//U/v4oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD+cj4ATD/gmT/wAFnvjR+yzquND/AGU/+Csn9u/tUfs0Tuv2Xw74Q/bE8J2VvD+0X8K7JsxWVnefEnRlsviHYQKER5o/D/h/S4pbqaVKAP6N6ACgD4S/4KhfFCP4L/8ABOH9ur4ntKIZ/CP7J/x4vdMcttzrl18N/EOmaBEGyCGn1u+0+FMfNukUKC2AwByn/BIX4YzfBz/glz+wD8PbuE2+oaP+yf8ABTUNXgZNjQ634o8EaT4s1uJl4IaPV9cvUbcNxIy2GJoA/RigAoAKAPwy/aQ/4Is6FH8W9c/a2/4JofHHxH/wTk/a81mUX/i+/wDhtpVtrX7N3x3uYrqS/ay+O/7Pt0yeENafUbmSYXHiTQrSyv4bi6udbu9M1vWQlxQB5ZZf8FQ/+ClH7GoTw1/wUx/4Jk/En4h+HtKEVrL+1l/wTfif4+/DDX4EY251/wAQ/BfUb6w+KPw4gkaMT3x1S4nTzbhRY6XFbBAoB2Fp/wAHM/8AwR0NpK3iD9o3xt4H1y2BS98G+NP2b/2itH8X2V2oHmWEmkx/DC8W4vImzE6WFzdxGRHWOV9poA8d8e/8FNv21/8AgphYXfwQ/wCCP/7OPxa+FPgrxjGdG8Zf8FKv2rfh9rHwn+F3wz8L3+yHVNc+A3w/8RxQ+Lviv4/GnXDv4dmfT7O20PUjbT6jo6wP/bGlAH69/sA/sJfBz/gnd+zp4e/Z9+ELavrrpqOpeMvib8T/ABZMt98QPjR8WPEzRXPjT4o+P9WLSTX/AIh8RXsaCKJ554tI0i10zRLWV7bT45ZQD7XoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA//V/v4oAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD8xP+CtP7Cur/t2fspX3hv4X60PBH7UvwP8AFugftC/sg/E6GeOwvvAv7QfwymfV/CX/ABM3jc2ejeLY1u/CGutIJLS3ttXi1ia2uZtGtEoA6H/glz+3vo3/AAUH/ZZ0H4najo//AAgfx28AavqPwg/ao+DN8r2niD4PftB+BGXSvHvhXVNJuD9tsNNvtQibX/C73O9pdA1K0tp5TqdjqdvbgH6NUAfgZ/wcb+JtU1r9gPw3+yT4Ru5YviL/AMFAf2ov2cP2QvB9pZjfqMtv41+JOk+KvF93HGDmOwtfCvg3UrTVLx1a3tINTj88qsysoB+7Hhnw9pXhHw34f8KaFbJZ6J4Y0TSvD2j2cYwlrpWi2Fvpun2yDskFpbQxKPRR6UAbdABQAUAFABQBk3eg6HqF1FfX2i6Te3sG3yLy706zubqHZnZ5VxNC8se0kldjrjnGKANagAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP/1v7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP57f27/2Y/2h/wBh/wDak1X/AIK2/wDBO7wBffFC78UaRpehf8FEv2LfDjm1n/ab+G3h5Nmn/GT4X2MSSW6ftD/DbTRM9vHDaT3njDTElgghur688Q6d4rAP0p/ZM/4KT/sV/tqfCJfjL8Dfjz4FvtB0+yefxx4b8V69pPg34gfCnULSHzNX0L4p+C9dvbbWfBeqaNIk8N5LqUK6Rci3kvdI1TVNLaHUJQD8lfg54wsv+Cv/APwVy8L/ALTnw/d/E3/BPr/glZpPjnwj8HPiLGry+C/2hf22fiXp8Gi+NfFvga6ISz8T+Dvg14LSCx07xDbCa3h8Vf2XrOiXd1pviFJUAP6U6ACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAP/9f+/igDz/W9N+Kdxql1N4b8ZfD/AEnRX8n7Hp+t/DTxH4g1S3228S3H2rV7D4teGbS7827WeaHytDsvIt5IrWT7TJC95cAGV/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAH9j/ABv/AOih/Cr/AMM14u/+fxQAf2P8b/8Aoofwq/8ADNeLv/n8UAH9j/G//oofwq/8M14u/wDn8UAH9j/G/wD6KH8Kv/DNeLv/AJ/FAB/Y/wAb/wDoofwq/wDDNeLv/n8UAH9j/G//AKKH8Kv/AAzXi7/5/FAB/Y/xv/6KH8Kv/DNeLv8A5/FAB/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAH9j/ABv/AOih/Cr/AMM14u/+fxQAf2P8b/8Aoofwq/8ADNeLv/n8UAH9j/G//oofwq/8M14u/wDn8UAH9j/G/wD6KH8Kv/DNeLv/AJ/FAB/Y/wAb/wDoofwq/wDDNeLv/n8UAH9j/G//AKKH8Kv/AAzXi7/5/FAB/Y/xv/6KH8Kv/DNeLv8A5/FAB/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAH9j/ABv/AOih/Cr/AMM14u/+fxQB+XP7Rn/BDz9iD9rL4kzfGD48/s3/ALKHjD4lXt4NR1rxdpnwZ+KvgLUvFF+GV2vfGS/Dr9pfwna+M72UoouLzxTbatdXCL5U0zxFkcA/Qj4X/BPxL8EvAPhf4V/B+f8AZ++GXw28FaZFo3hPwN4G/Z913w14X8P6ZCWZbXTNH0r432tlbLJK8lxcSJD511dSz3d1JLczTSuAd9/Y/wAb/wDoofwq/wDDNeLv/n8UAH9j/G//AKKH8Kv/AAzXi7/5/FAB/Y/xv/6KH8Kv/DNeLv8A5/FAB/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAH9j/ABv/AOih/Cr/AMM14u/+fxQAf2P8b/8Aoofwq/8ADNeLv/n8UAH9j/G//oofwq/8M14u/wDn8UAH9j/G/wD6KH8Kv/DNeLv/AJ/FAB/Y/wAb/wDoofwq/wDDNeLv/n8UAH9j/G//AKKH8Kv/AAzXi7/5/FAB/Y/xv/6KH8Kv/DNeLv8A5/FAB/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAH9j/ABv/AOih/Cr/AMM14u/+fxQAf2P8b/8Aoofwq/8ADNeLv/n8UAH9j/G//oofwq/8M14u/wDn8UAH9j/G/wD6KH8Kv/DNeLv/AJ/FAB/Y/wAb/wDoofwq/wDDNeLv/n8UAH9j/G//AKKH8Kv/AAzXi7/5/FAB/Y/xv/6KH8Kv/DNeLv8A5/FAB/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAH9j/ABv/AOih/Cr/AMM14u/+fxQAf2P8b/8Aoofwq/8ADNeLv/n8UAH9j/G//oofwq/8M14u/wDn8UAH9j/G/wD6KH8Kv/DNeLv/AJ/FAB/Y/wAb/wDoofwq/wDDNeLv/n8UAH9j/G//AKKH8Kv/AAzXi7/5/FAB/Y/xv/6KH8Kv/DNeLv8A5/FAB/Y/xv8A+ih/Cr/wzXi7/wCfxQAf2P8AG/8A6KH8Kv8AwzXi7/5/FAB/Y/xv/wCih/Cr/wAM14u/+fxQAf2P8b/+ih/Cr/wzXi7/AOfxQAf2P8b/APoofwq/8M14u/8An8UAeq0AFAH/0P7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/0f7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/0v7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/0/7+KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD/2Q=='

        # Add plans to the provider
        Given path `Providers/${providerDetails.providerId}/Plans`
        When request { "providerId": #(providerDetails.providerId), "addedPlans": [{ "planId": #(providerConfig.planId) }]}
        And retry until responseStatus == 200   
        When method POST
        Then status 200

        # Add provider licensing
        Given path 'ProviderLicensedState'
        And request { "providerId": #(providerDetails.providerId), "stateAbrv": #(providerConfig.providerLicensedState), "expirationDate": "2025-12-31T00:00:00.000Z", "isApproved": true, "licenseType": "StateLicense" }
        And retry until responseStatus == 200   
        When method PUT
        Then status 200

        # Update provider credentials
        Given path `Providers/${providerDetails.providerId}/Credential`
        And request
            """
            {
                "providerId": #(providerDetails.providerId),
                "backGroundCheckInitiated": true,
                "backGroundCheckPassed": true,
                "backGroundCheckCompletedDate": "2021-06-01T15:03:52.241Z",
                "credentialDate": "2021-06-01T15:03:52.241Z",
                "initialCredentialDate": "2021-06-01T15:03:52.241Z",
                "notInOfficeofInspectorGeneralExclusionListCheckedDate": "2021-06-01T15:03:52.241Z",
                "isNotInOfficeofInspectorGeneralExclusionList": true,
                "notInGeneralServicesAdministrationExclusionListCheckedDate": "2021-06-01T15:03:52.241Z",
                "isNotInGeneralServicesAdministrationExclusionList": true,
                "completedContractApplication": true,
                "recruiterUserId": 1,
                "isCredentialCca": true,
                "badgeId": "123456",
                "dateMailedBadge": "2021-06-01T15:03:52.241Z",
                "isNationalCredentialingOrganizationInformationTracked": true,
                "isCenseoHealthInformationTracked": true,
                "hasMalpracticeRecord": true,
                "hasDisciplinaryActions": true,
                "isEnrolledMedicare": true,
                "badgePhotoReceived": true,
                "isCredentialByOther": true,
                "staffingOrganization": "DataGenMatchMaker",
                "isWorkHistoryVerified": true,
                "dateWorkHistoryVerified": "2021-06-01T15:03:52.241Z",
                "verifiedBy": 1,
                "receivedW9": true,
                "internetSearchCompleted": true,
                "clinicalContingentWorkerAgreementSigned": true,
                "pendingMalpracticeClaims": true,
                "drugScreenOrdered": "2021-06-01T15:03:52.241Z",
                "drugScreenCompleted": "2021-06-01T15:03:52.241Z",
                "drugScreenPassed": true,
                "currentAppointmentEndDate": "3001-06-01T15:03:52.241Z",
                "currentAppointmentStartDate": "2021-06-01T15:03:52.241Z"
            }
            """
        And retry until responseStatus == 200   
        When method Post
        Then status 200

        Given path 'Credential'
        And request
            """
            {
            "ProviderId": #(providerDetails.providerId),
            "PatchCredentialDocument": [
            { "value": 2, "path": "/CredentialStatusId", "op": "replace" },
            { "value": "DataGenMatchMaker", "path": "/StaffingOrganization", "op": "replace" }
            ]
            }
            """
        And retry until responseStatus == 200   
        When method Patch
        Then status 200

        # Approve the credentials
        Given path `Providers/${providerDetails.providerId}/ProviderPlan/CredentialStatus`
        And request {"planIds": [#(providerConfig.planId)], "credentialStatus": 2 }
        And retry until responseStatus == 200   
        When method Patch
        Then status 200

        # Patch provider for in home
        Given path `providers/${providerDetails.providerId}/plan/${providerConfig.planId}`
        And request [{"value": true,  "path": "/CanSeeInHome", "op": "replace"}]
        And retry until responseStatus == 200   
        When method Patch
        Then status 200

        # Add capacity
        Given url capacityApi
        And path 'Capacity'
        And request
            """
            {
                "availabilityStatus": 6,
                "planId": #(providerConfig.planId),
                "ownerId": #(providerDetails.providerId),
                "startDate": "#(DataGen().isoDateStamp())",
                "endDate": "#(DataGen().isoDateStamp())",
                "locationType": 1,
                "state": "TX",
                "county": "Dallas County",
                "addressLineOne": "4055 Valley View ln",
                "city": "Dallas",
                "zipCode": "75244",
                "hasDummyPlan": false,
                "weekDays": [
                    {
                        "weekday": #(DataGen().todayAsNumber()),
                        "startTime": "06:00:00",
                        "endTime": "18:00:00",
                        "lunchDuration": 30,
                        "lunchStartTime": "12:00:00"
                    }
                ],
                "averageEvaluationTimeInMinutes": 30,
                "staticLocationDescription": "Location Notes from DataGenMatchMaker",
                "oktaUserId": "#(okta.clientId)"
            }
            """
        And retry until responseStatus == 200   
        When method POST
        Then status 200
        And match response.success == '#[_ > 0]'
        And match response.notSuccess == '##[]'

        Given path 'Capacity'
        And param ownerId = providerDetails.providerId
        And param startDate = DataGen().isoDateStamp()
        And param endDate = DataGen().isoDateStamp(2)
        And retry until responseStatus == 200   
        When method Get
        Then status 200
        And match response == '#[_ > 0]'
        And match each response..availabilityStatus == 6
        * def providerAvailabilityDetailId = response[0].providerAvailabilityDetailId

        # Approve the capacity
        Given path `Capacity/${providerAvailabilityDetailId}`
        And request
        """
            {
                "patchDocument": [
                    {
                        "value": "3",
                        "path": "/ProviderAvailabilityStatusId",
                        "op": "add"
                    },
                    {
                        "value": "32.665960",
                        "path": "/Latitude",
                        "op": "add"
                    },
                    {
                        "value": "-97.012620",
                        "path": "/Longitude",
                        "op": "add"
                    }
                ],
                "PatchCapacityAction": "Approve"
            }
        """
        And retry until responseStatus == 200   
        When method PATCH
        Then status 200