CREATE TABLE "A1CBarcodeHistory"
(
	"A1CBarcodeHistoryId" SERIAL PRIMARY KEY,
    "A1CId" INTEGER NOT NULL REFERENCES "A1C"("A1CId"),
    "Barcode" VARCHAR(200) NOT NULL,
	"CreatedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL
);