using System.Diagnostics.CodeAnalysis;

namespace Signify.Spirometry.Core.ApiClients.ProviderPayApi.Responses;

[ExcludeFromCodeCoverage]
public class ProviderPayApiResponse
{
    /// <summary>
    /// Unique Guid generated by ProviderPay API used to track a payment
    /// </summary>
    public string PaymentId { get; set; }
}