apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: signify-egfr-svc
  description: eGFR Process Manager
  annotations:
    backstage.io/techdocs-ref: dir:.
  #    dev.azure.com/project-repo: HCC/ancillary # Leaving out for now until this is moved out of a mono-repo, as to avoid noise from the other process managers being displayed
  tags:
    - ancillary
    - dps
    - labrats
    - dpsi
    - egfr
    - ked
    - tier3
  links:
    - url: https://cvs-hcd.atlassian.net/wiki/spaces/AncillarySvcs/pages/51222080/eGFR+Process+Manager
      title: eGFR Process Manager
spec:
  type: service
  lifecycle: production
  owner: group:dps
  system: dps
  dependsOn:
    - resource:egfr-db
    - Resource:kafka
  providesApis:
    - egfr-kafka-events
  consumesApis: # These must match exactly as they are named in their API in Backstage for Backstage to properly link them
    - appointment-api
    - cdi-api
    - evaluation
    - member
    - labs # Labs API
    - labs-events # Kafka events from Labs Home Access
    - okta
    # - pdfdelivery # this is missing here because it's not configured in backstage. This is where it comes from: https://dev.azure.com/signifyhealth/HCC/_git/coreservices?version=GBmaster&_a=contents&path=/onprem/signify.cap.kafkapublisher. Should be added when available.
    - provider
    - providerpay
    - rcm
    - rms-lab-result-internal-api-events
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: egfr-db
  description: Database for the eGFR Process Manager
  tags:
    - ancillary
    - dps
    - labrats
    - dpsi
    - postgres
    - egfr-db
spec:
  type: database
  lifecycle: production
  owner: group:dps
  system: dps
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: egfr-kafka-events
  description: eGFR Kafka Events API
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - kafka
    - json
  links:
    - url: https://cvs-hcd.atlassian.net/wiki/spaces/AncillarySvcs/pages/51219165/Lab+Status+Contracts
      title: eGFR Status Contract
    - url: https://cvs-hcd.atlassian.net/wiki/spaces/AncillarySvcs/pages/51219279/Lab+Result+Contracts
      title: eGFR Result Contract
spec:
  type: asyncapi
  lifecycle: production
  owner: group:dps
  system: dps
  definition:
    $text: https://dev.azure.com/signifyhealth/HCC/_git/ancillary?path=/service/egfr/docs/asyncapi.yaml