#Only triggered manually
trigger: none

variables:
  - group: ancillary-qe-pipeline-uat
  - name: flyway
    value: false
resources:
  repositories:
    - repository: templates
      type: git
      name: HCC/templates
jobs:
  - template: automated-system-tests.yaml