parameters:
  - name: envVariables
    type: object
    default:
      - name: RancherToken
        value: $(RancherToken)
      - name: ClusterId
        value: $(ClusterId)
      - name: DOTNET_CLI_HOME
        value: '$(Agent.TempDirectory)'
  - name: runSettingsFilePath
    type: string
    default: $(Build.Repository.Name)/service/uacr/prodTests/Signify.uACR.Production.Tests/RunSettings/prod.runsettings
  - name: testCycleName
    type: string
    default: 'Test Automation Run for Commit : $(Build.SourceVersion) (CECG)-PROD'
  - name: dotnetVersion
    type: string
    default: '8.0.x'
  - name: GitVersion
    type: string
    default: ''
  - name: CommitId
    type: string
    default: '$(Build.SourceVersion)'

jobs:
  - job: Dotnet_System_Tests
    displayName: Dotnet.System.Tests
    pool: uat-linux-test
    variables:
      - group: qe-common-zephyr
      - name: testFilter
        value: '"TestCategory=prod_readiness"'
    steps:
      - checkout: self
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '${{ parameters.dotnetVersion }}'
      - task: DotNetCoreCLI@2
        displayName: dotnet test
        inputs:
          command: test
          projects: $(Build.SourcesDirectory)/$(Build.Repository.Name)/service/uacr/prodTests/Signify.uACR.Production.Tests/Signify.uACR.Production.Tests.csproj
          arguments: '--configuration Test -s ${{parameters.runSettingsFilePath}} --logger:"console;verbosity=detailed" --filter ${{variables.testFilter}}'
          publishTestResults: true
          nobuild: false
        env:
          ${{ each envVariable in parameters.envVariables }}:
            ${{ envVariable.name }}: ${{ envVariable.value }}
          GitVersion: ${{ parameters.GitVersion }}
          CommitId: ${{ parameters.CommitId }}
          NameSpace: 'uacr'
      - template: steptemplates/zephyr-create-test-cycle.yaml@templates
        parameters:
          zephyrApiUrl: '$(ZEPHYR_API_URL)ANC'
          zephyrApiToken: $(ZEPHYR_API_TOKEN)
          testResultsFilePath: '$(Agent.TempDirectory)/*.trx'
          jiraProjectKey: 'ANC'
          testCycleName: ${{ parameters.testCycleName }}
...